alias l='ls -lah' 
alias ls='eza'
alias art='php artisan'
alias dkc='docker compose'
alias dkcp='docker compose -f docker-compose.prod.yml'
alias dk='docker'
alias c='clear'
alias :q='exit'
alias :q!='shutdown now'
alias ssh='TERM=screen ssh'
